---
- name: Setup infrastructure
  hosts: local
  tasks:
    - name: Add secrets.auto.tfvars
      ansible.builtin.template:
        src: secrets.auto.tfvars.j2
        dest: '{{ terraform_dir }}/secrets.auto.tfvars'
        mode: '0644'

    - name: Apply terraform infrastructure (webservers, loadbalancer, domain)
      community.general.terraform:
        project_path: '{{ terraform_dir }}'
        force_init: true
        purge_workspace: false
        workspace: 'hexlet77'
        lock: true
        state: '{{ infra_state }}'
      register: infra

    - name: Add hosts
      ansible.builtin.template:
        src: hosts.j2
        dest: hosts.ini
        mode: '0644'
      changed_when: infra_state == 'present'

    - name: Update env file
      ansible.builtin.template:
        src: env.j2
        dest: files/.env
        mode: '0644'
